
remote_theme: alejandroliu/cayman-blog

title: 0ink.net
description: Not the site you were looking for

show_downloads: false

header_pages:
  - about.md
  - privacy-policy.md

# imghdr: under-construction.png
imghdr: pig_med.png

# Hard coding https
url: https://www.0ink.net/

# Enable site search
search:
  sites: 0ink.net
  prefill: Search DuckDuckGo

plugins:
  - jekyll-sitemap
 
