#!/bin/sh
xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn 9x15bold -exitOnFail
candy=""

#~ pick_hack() {
  #~ set - starwars atlantis pyro rocks unknownpleasures
  # boing bouboule
  #~ local n=$(expr $RANDOM % $#)
  #~ eval "echo '$'$n"
#~ }
#candy="display -window root /home/alex/bg/event-horizon-2-1920×1080.jpg"

pick_hack() {
  set - phosphor xmatrix boing starwars unknownpleasures pyro atlantis bouboule rocks glmatrix
  local n=$(expr $(date +%s) % $# + 1)
  eval "local hack='$'$n"
  echo "/usr/libexec/xscreensaver/$hack -root"
}
candy=$(pick_hack)

if [ -n "$candy" ] ; then
  (
    export HOME=/root
    $candy &
    echo $! > /var/run/xdm-candy.pid
  )
fi


