#!/bin/sh
xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn 9x15bold -exitOnFail
candy=""

#~ pick_hack() {
  #~ set - starwars atlantis pyro rocks unknownpleasures
  # boing bouboule
  #~ local n=$(expr $RANDOM % $#)
  #~ eval "echo '$'$n"
#~ }
#candy="display -window root /home/alex/bg/event-horizon-2-1920×1080.jpg"

case "$(date +%m)" in
02)
  candy="/usr/libexec/xscreensaver/xmatrix -root"
  ;;
04)
  candy="/usr/libexec/xscreensaver/boing -root"
  ;;
05)
  candy="/usr/libexec/xscreensaver/starwars -root"
  ;;
06)
  candy="/usr/libexec/xscreensaver/unknownpleasures -root"
  ;;
07)
  candy="/usr/libexec/xscreensaver/pyro -root"
  ;;
08)
  candy="/usr/libexec/xscreensaver/atlantis -root"
  ;;
09)
  candy="/usr/libexec/xscreensaver/bouboule -root"
  ;;
10)
  candy="/usr/libexec/xscreensaver/rocks -root"
  ;;
*)
  candy="/usr/libexec/xscreensaver/glmatrix -root"
  ;;
esac

if [ -n "$candy" ] ; then
  $candy &
  echo $! > /var/run/xdm-candy.pid
fi


