#!/bin/sh
#
if xpid=$(pidof Xorg) ; then
  DISPLAY=":0.0"
  XAUTHORITY=""
  set - $(tr '\0' ' ' </proc/$xpid/cmdline)
  while [ $# -gt 0 ]
  do
    case "$1" in
    -auth)
      XAUTHORITY="$2" ; shift
      ;;
    esac
    shift
  done
  export DISPLAY XAUTHORITY
  output=$(xrandr) || exit 1
  port=$(echo "$output" | awk '$2 == "connected" { print $1 }')
  [ -z "$port" ] && exit 0
  xrandr --output "$port" --auto
  sleep 1
  xrefresh
fi

